DROP DATABASE IF EXISTS extravagance;
CREATE DATABASE extravagance;
USE extravagance;
/* CREATE TABLE IF NOT EXISTS datosUsuario(
	idUsuario INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    primerNombre VARCHAR(20) NOT NULL,
    segundoNombre VARCHAR(20),
    primerApellido VARCHAR(20) NOT NULL,
    segundoApellido VARCHAR(20),
    correo VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
*/
CREATE TABLE IF NOT EXISTS usuario(
	idUsuario INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    correo VARCHAR(30) NOT NULL,
    contraseña VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- SELECT * FROM usuario


